-- Runny başlangıç şeması
-- Supabase Dashboard > SQL Editor bölümünde çalıştırılabilir.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nickname text not null unique,
  display_name text,
  avatar_url text,
  bio text,
  profession text,
  age integer,
  location text,
  sports text[] not null default '{}',
  equipment text[] not null default '{}',
  sport_goals jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.activities (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  type text not null check (type in ('run', 'walk', 'bike', 'hike', 'swim', 'trail', 'gym', 'yoga')),
  title text not null,
  location_name text,
  distance_meters numeric not null default 0,
  duration_seconds integer not null default 0,
  avg_pace_seconds numeric,
  calories integer,
  elevation_gain_meters numeric not null default 0,
  avg_heart_rate integer,
  max_heart_rate integer,
  is_public boolean not null default true,
  started_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.activity_points (
  id bigint generated by default as identity primary key,
  activity_id uuid not null references public.activities(id) on delete cascade,
  sequence_number integer not null,
  latitude double precision not null,
  longitude double precision not null,
  altitude double precision,
  recorded_at timestamptz not null
);

create table if not exists public.follows (
  follower_id uuid not null references public.profiles(id) on delete cascade,
  following_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (follower_id, following_id),
  check (follower_id <> following_id)
);

create table if not exists public.likes (
  user_id uuid not null references public.profiles(id) on delete cascade,
  activity_id uuid not null references public.activities(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, activity_id)
);

create table if not exists public.comments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  activity_id uuid not null references public.activities(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 500),
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.activities enable row level security;
alter table public.activity_points enable row level security;
alter table public.follows enable row level security;
alter table public.likes enable row level security;
alter table public.comments enable row level security;

create policy "Public profiles are viewable"
  on public.profiles for select using (true);
create policy "Users can update own profile"
  on public.profiles for update using (auth.uid() = id);
create policy "Users can insert own profile"
  on public.profiles for insert with check (auth.uid() = id);

create policy "Public activities are viewable"
  on public.activities for select
  using (is_public or auth.uid() = user_id);
create policy "Users can create own activities"
  on public.activities for insert with check (auth.uid() = user_id);
create policy "Users can update own activities"
  on public.activities for update using (auth.uid() = user_id);
create policy "Users can delete own activities"
  on public.activities for delete using (auth.uid() = user_id);

create policy "Activity points follow activity visibility"
  on public.activity_points for select
  using (
    exists (
      select 1 from public.activities
      where activities.id = activity_points.activity_id
        and (activities.is_public or activities.user_id = auth.uid())
    )
  );
create policy "Users can add points to own activity"
  on public.activity_points for insert
  with check (
    exists (
      select 1 from public.activities
      where activities.id = activity_points.activity_id
        and activities.user_id = auth.uid()
    )
  );

create policy "Follows are viewable"
  on public.follows for select using (true);
create policy "Users manage own follows"
  on public.follows for all
  using (auth.uid() = follower_id)
  with check (auth.uid() = follower_id);

create policy "Likes are viewable"
  on public.likes for select using (true);
create policy "Users manage own likes"
  on public.likes for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Comments are viewable"
  on public.comments for select using (true);
create policy "Users create own comments"
  on public.comments for insert with check (auth.uid() = user_id);
create policy "Users delete own comments"
  on public.comments for delete using (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, nickname, display_name)
  values (
    new.id,
    'user_' || substr(replace(new.id::text, '-', ''), 1, 10),
    coalesce(new.raw_user_meta_data ->> 'full_name', new.email)
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

grant usage on schema public to anon, authenticated, service_role;
grant select, insert, update, delete on table public.profiles to anon, authenticated;
grant select, insert, update, delete on table public.activities to anon, authenticated;
grant select, insert, update, delete on table public.activity_points to anon, authenticated;
grant select, insert, update, delete on table public.follows to anon, authenticated;
grant select, insert, update, delete on table public.likes to anon, authenticated;
grant select, insert, update, delete on table public.comments to anon, authenticated;
grant all on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to anon, authenticated, service_role;
